### ISSUE TITLE
Webpack builds cause database seed to re-run when building during debugging

### ISSUE THREAD

**Issue by IronSean** [JonJam/aspnet_with_webpack#4]
When I'm using a project based on this, and I run the project and load my page, I get funny behaviour editing in place.

When the bundle is build and the project starts debugging, VS will take it's time, compile, JIT, and run the database Seed through Entity Framework. Then I change the js source files, and re-reun npm-task-runner's build script to regenerate the bundle. Now when I refresh the page to see the new bundle load... EF re-reuns the database seed method, plus who knows what else.

Just wondered if you guys had come across this as well.

**Comment by JonJam** [comment]
Hi @IronSean, 

No I haven't come across this before, as I haven't used this project in combination with SQL/Entity Framework.

I don't suppose your project is on GitHub to take a look at?

**Comment by JonJam** [comment]
Closing this since no reply.

More than happy to re-open.

**Comment by IronSean** [comment]
Sorry for lack of reply, no project on github that we can test on yet, if I get one up I'll request we re-open.

Running webpack build with `-watch` allows incremental rebuilds, and doesn't trigger a database reseed when it happens so that's been the easiest workflow in the meantime if anyone else ends up here.

**Comment by JonJam** [comment]
Thanks @IronSean for posting a workaround.
