### ISSUE TITLE
window flickers unstyled content before bootstrap is loaded

### ISSUE THREAD

**Issue by colinwurtz** [JonJam/aspnet_with_webpack#5]
First of all, thanks for the great blog post. It's been the best one I've been able to find in order to do this.

When loading the home page, I get a slight flicker of unstyled content before the bootstrap css gets loaded. I'm assuming it has to do where webpack is injecting the bundle. Do you have a recommended way of making sure the css is loaded first in this setup? Thanks.

![unstyled](https://user-images.githubusercontent.com/3066044/36824283-1c90a422-1cc7-11e8-9602-81c707c536ad.gif)

**Comment by colinwurtz** [comment]
Nevermind, I didn't even notice you had the config needed for this set up in `webpack.prod.js`

**Comment by JonJam** [comment]
Hi @colinwurtz , sorry I was going to reply to this yesterday but got busy with other things and dealing with the UK weather.

Thanks very much, glad you like the post and glad you fixed it :)
