### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by berkansivri** [JonJam/aspnet_with_webpack#6]
Hello,

I just want to learn do I need anything(!) to install in production server when I use webpack, es6, npm, gulp etc...
I am asking for, there is already running mvc5 project on this server and I am totally forbidden to install anything to server. That's why, does mvc5 project with webpack can run on same server without need any installation ?

**Comment by JonJam** [comment]
Hi @berkansivri, no you don't need to install anything on the production server.

No you don't need to install anything on the production server. You just need to ensure that at build time you run the necessary npm scripts i.e. build:prod  to build your JS/CSS assets and ensure they are copied to your production server .

**Comment by berkansivri** [comment]
Last question @JonJam , this project will be use in IE11 only. I research some and realize that I need the use babel. Is there any problem that you can see ? I want to use latest syntax on my project.

**Comment by JonJam** [comment]
I haven't used babel, but you will need to check what JS features you want to use and whether babel can transpile them to support IE11. For example, promises would require a polyfill on IE11.

**Comment by berkansivri** [comment]
Thank you...
